import Head from 'next/head'
import FrontPage from '@components/frontpage'
const Home = () => {
  return (
    <>
      <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container-fluid'>
        <FrontPage/>
      </div>
    </>
  )
}

export default Home